// Canonical spelling for tags, applied wherever tags are computed.
//
// Two producers disagreed on spelling: the regex taxonomy emitted British
// `-isation`, the LLM classifier emitted American `-ization`. That split the same
// concept across two pages — /tags/quantisation/ held 654 posts and
// /tags/quantization/ another 214. American wins because it is what the source
// material and the wider ML ecosystem use, and because it was already dominant
// here (inference-optimization 324 posts vs inference-optimisation 1).
//
// The rule is deliberately scoped to the two stems that actually occur rather
// than a general s -> z rewrite. A blanket rule would corrupt real tags:
// `supervised-fine-tuning-dataset` and `audio-denoising` both contain an
// innocent "is" and must survive untouched.
const SPELLING = /(optimi|quanti)s/g;

// Distinct concepts that arrived under more than one name.
//
// The separator-variant block below is generated by scripts/find-tag-collisions.js,
// which finds tags that are identical once every non-alphanumeric character is
// stripped. Left unmerged these split one subject over two half-empty pages:
// /tags/qwen-3-8-27b/ held 5 posts and /tags/qwen3-8-27b/ another 4, for one model.
//
// The merge is listed explicitly rather than derived from a rule. The obvious rule —
// insert a hyphen between a letter-run and a digit-run — would rewrite `gpt4all` to
// `gpt-4-all` and `lfm2` to `lfm-2`, breaking real product names. That is the same
// trap the SPELLING regex above is deliberately scoped to avoid.
//
// The surviving spelling is the more frequent one, which in every case here also
// matches the slug convention already used elsewhere (dots and spaces become hyphens,
// as in llama.cpp -> llama-cpp). Re-run the detector after any retag; new tags arrive
// from an open-ended LLM vocabulary and will collide again.
const EXPLICIT = {
  benchmark: "benchmarks",

  // Separator variants — see scripts/find-tag-collisions.js
  "multi-modal-ai": "multimodal-ai",
  // Repointed from "multimodal" when that became an alias itself (see SAME_REFERENT
  // below). canonicalTag does a single lookup and does not chain, so an alias whose
  // destination is itself aliased would strand on a slug that no longer has a page.
  "multi-modal": "multimodal-ai",
  "howtogeek": "how-to-geek",
  "startupfortune": "startup-fortune",
  "prism-ml": "prismml",
  "qwen3-8-27b": "qwen-3-8-27b",
  "vscode": "vs-code",
  "hardware-software-codesign": "hardware-software-co-design",
  "multitoken-prediction": "multi-token-prediction",
  "cicd-integration": "ci-cd-integration",
  "kvcache": "kv-cache",
  "homelab": "home-lab",
  "qoomedia": "qoo-media",
  "lfm2-5": "lfm-2-5",
  "local-model-finetuning": "local-model-fine-tuning",
  "turbo-quant": "turboquant",
  "nextjs": "next-js",
  "transformersjs": "transformers-js",
  "trendhunter": "trend-hunter",
  "togetherai": "together-ai",
  "qwen-35-optimization": "qwen-3-5-optimization",
  "realtime-ai-applications": "real-time-ai-applications",
  "neuralkore": "neural-kore",
  "savvycanary": "savvy-canary",
  "apexcovantage": "apex-covantage",
  "kogai": "kog-ai",
  "exoplatform": "exo-platform",

  // Both of these invert the detector's "most frequent variant wins" suggestion,
  // which the script itself flags for verification against vendor spelling.
  //
  // qwen: the detector prefers qwen3-8-flash-next (7 posts vs 1), but qwen-3-8-27b
  // above is already canonical in the hyphenated form. One model family cannot use
  // two slug conventions, and consistency beats a 7-to-1 count on tags this small.
  "qwen3-8-flash-next": "qwen-3-8-flash-next",
  // coreml: the detector prefers coreml (2 vs 1). Apple writes "Core ML", and the
  // dots-and-spaces-become-hyphens convention used for llama.cpp -> llama-cpp gives
  // the same answer, so vendor spelling and house style agree against frequency.
  "coreml": "core-ml",
};

// Synonyms that find-tag-collisions.js cannot see. That detector compares tags after
// stripping non-alphanumerics, so it only finds variants that are spelled alike —
// `mcp` and `model-context-protocol` share no characters and read as unrelated.
// A tag co-occurrence pass over the corpus surfaces them instead: these pairs sit at
// the top of the graph by Jaccard overlap, which is what one concept split across two
// nodes looks like.
//
// The test applied is SAME REFERENT, not merely related. `mcp` and
// `model-context-protocol` name one protocol, so they merge. `apple` and
// `apple-silicon` do not — one is a company and the other a chip family — and
// `release` and `model-release` do not, so both stay split however tempting the
// overlap looks. Merging on relatedness rather than identity is how an open
// vocabulary collapses into a generic one.
//
// Where frequency and specificity disagree the more specific slug wins, matching the
// instruction the tagger itself is given ("prefer iterative-reasoning over generic
// reasoning"): hence evaluation -> model-evaluation against the count.
const SAME_REFERENT = {
  "mcp": "model-context-protocol",       // 29 + 32 posts, J=0.49 — highest edge in the graph
  "multimodal": "multimodal-ai",         // 24 + 44
  "model-quantization": "quantization",  // 243 + 312 — largest merge here
  "rag-pipeline": "rag",                 // 34 + 35
  "coding": "code-generation",           // 26 + 69
  "evaluation": "model-evaluation",      // 24 + 21, specificity over frequency
  "ai-sovereignty": "sovereign-ai",      // 1 + 10; takes sovereign-ai over the page threshold
};

// Deliberately NOT merged into sovereign-ai, recorded so the question is not reopened:
//
//   data-sovereignty (37)      where data legally sits — a jurisdiction question that
//                              applies whether or not any AI is involved
//   digital-sovereignty (1)    the umbrella policy concept over cloud, chips and data
//   sovereign-computing (1)    control of the compute layer
//   operational-sovereignty (1) control of how a system is run
//
// All four overlap with sovereign-ai and none is the same thing. The last three carry
// one post each, below MIN_POSTS_FOR_TAG_PAGE, so they render nowhere and collapsing
// them would buy no page while destroying the distinction a guide on this subject
// exists to draw.

Object.assign(EXPLICIT, SAME_REFERENT);

function canonicalTag(tag) {
  if (typeof tag !== "string") return tag;
  const normalised = tag.replace(SPELLING, "$1z");
  // Look up case-insensitively: the LLM emits the same slug in mixed casing
  // ("MediaTek", "mediatek"), and a case-sensitive lookup would let one variant
  // past the alias map and back onto its own page.
  return EXPLICIT[normalised.toLowerCase()] || normalised;
}

module.exports = { canonicalTag };
