// Canonical spelling for tags, applied wherever tags are computed.
//
// Two producers disagreed on spelling: the regex taxonomy emitted British
// `-isation`, the LLM classifier emitted American `-ization`. That split the same
// concept across two pages — /tags/quantisation/ held 654 posts and
// /tags/quantization/ another 214. American wins because it is what the source
// material and the wider ML ecosystem use, and because it was already dominant
// here (inference-optimization 324 posts vs inference-optimisation 1).
//
// The rule is deliberately scoped to the two stems that actually occur rather
// than a general s -> z rewrite. A blanket rule would corrupt real tags:
// `supervised-fine-tuning-dataset` and `audio-denoising` both contain an
// innocent "is" and must survive untouched.
const SPELLING = /(optimi|quanti)s/g;

// Distinct concepts that arrived under more than one name.
//
// The separator-variant block below is generated by scripts/find-tag-collisions.js,
// which finds tags that are identical once every non-alphanumeric character is
// stripped. Left unmerged these split one subject over two half-empty pages:
// /tags/qwen-3-8-27b/ held 5 posts and /tags/qwen3-8-27b/ another 4, for one model.
//
// The merge is listed explicitly rather than derived from a rule. The obvious rule —
// insert a hyphen between a letter-run and a digit-run — would rewrite `gpt4all` to
// `gpt-4-all` and `lfm2` to `lfm-2`, breaking real product names. That is the same
// trap the SPELLING regex above is deliberately scoped to avoid.
//
// The surviving spelling is the more frequent one, which in every case here also
// matches the slug convention already used elsewhere (dots and spaces become hyphens,
// as in llama.cpp -> llama-cpp). Re-run the detector after any retag; new tags arrive
// from an open-ended LLM vocabulary and will collide again.
const EXPLICIT = {
  benchmark: "benchmarks",

  // Separator variants — see scripts/find-tag-collisions.js
  "multi-modal-ai": "multimodal-ai",
  "multi-modal": "multimodal",
  "howtogeek": "how-to-geek",
  "startupfortune": "startup-fortune",
  "prism-ml": "prismml",
  "qwen3-8-27b": "qwen-3-8-27b",
  "vscode": "vs-code",
  "hardware-software-codesign": "hardware-software-co-design",
  "multitoken-prediction": "multi-token-prediction",
  "cicd-integration": "ci-cd-integration",
  "kvcache": "kv-cache",
  "homelab": "home-lab",
  "qoomedia": "qoo-media",
  "lfm2-5": "lfm-2-5",
  "local-model-finetuning": "local-model-fine-tuning",
  "turbo-quant": "turboquant",
  "nextjs": "next-js",
  "transformersjs": "transformers-js",
  "trendhunter": "trend-hunter",
  "togetherai": "together-ai",
  "qwen-35-optimization": "qwen-3-5-optimization",
  "realtime-ai-applications": "real-time-ai-applications",
  "neuralkore": "neural-kore",
  "savvycanary": "savvy-canary",
  "apexcovantage": "apex-covantage",
  "kogai": "kog-ai",
  "exoplatform": "exo-platform",
};

function canonicalTag(tag) {
  if (typeof tag !== "string") return tag;
  const normalised = tag.replace(SPELLING, "$1z");
  // Look up case-insensitively: the LLM emits the same slug in mixed casing
  // ("MediaTek", "mediatek"), and a case-sensitive lookup would let one variant
  // past the alias map and back onto its own page.
  return EXPLICIT[normalised.toLowerCase()] || normalised;
}

module.exports = { canonicalTag };
